import argparse

import torch

from client import Client
from datasets.dataset_read import dataset_read
from models.get_dataset_specific_models import get_dataset_specific_generator, get_dataset_specific_classifier #...generator: gibt Digit5/Office Caltech/Office #...classifier: gibt entsprechende Prediciton (Label)
from server import Server
from utils.setup_fl_process import dataset_domain_sample_count_mapping, get_source_and_target_domains, arg_str_to_bool


'''
screen -dmS digit-five_no_augmentations sh -c 'docker run --gpus \"device=0\" --name jlehner_job3 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_no_aug --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_adjust_sharpness_05 sh -c 'docker run --gpus \"device=1\" --name jlehner_job4 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_adjust_sharpness_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_adjust_sharpness_1 sh -c 'docker run --gpus \"device=2\" --name jlehner_job5 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_adjust_sharpness_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_invert_05 sh -c 'docker run --gpus \"device=3\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_invert_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_invert_1 sh -c 'docker run --gpus \"device=4\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_invert_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_adjust_sharpness_05_invert_05 sh -c 'docker run --gpus \"device=5\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_ajust_sharpness_05_invert_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_adjust_sharpness_1_invert_05 sh -c 'docker run --gpus \"device=0\" --name jlehner_job9 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_adjust_sharpness_1_invert_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_adjust_sharpness_1_invert_1 sh -c 'docker run --gpus \"device=1\" --name jlehner_job10 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_adjust_sharpness_1_invert_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_adjust_sharpness_05_invert_1 sh -c 'docker run --gpus \"device=2\" --name jlehner_job11 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_adjust_sharpness_05_invert_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Brightness_02 sh -c 'docker run --gpus \"device=3\" --name jlehner_job12 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_brightness_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Brightness_04 sh -c 'docker run --gpus \"device=4\" --name jlehner_job13 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_brightness_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Brightness_06 sh -c 'docker run --gpus \"device=5\" --name jlehner_job14 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_brightness_06 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Brightness_08 sh -c 'docker run --gpus \"device=0\" --name jlehner_job15 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_brightness_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Brightness_1 sh -c 'docker run --gpus \"device=1\" --name jlehner_job16 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_brightness_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Contrast_02 sh -c 'docker run --gpus \"device=2\" --name jlehner_job17 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_contrast_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Contrast_04 sh -c 'docker run --gpus \"device=3\" --name jlehner_job18 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_contrast_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Contrast_06 sh -c 'docker run --gpus \"device=4\" --name jlehner_job19 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_contrast_06 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Contrast_08 sh -c 'docker run --gpus \"device=5\" --name jlehner_job20 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_contrast_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Contrast_1 sh -c 'docker run --gpus \"device=0\" --name jlehner_job21 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_contrast_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Saturation_02 sh -c 'docker run --gpus \"device=1\" --name jlehner_job22 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_saturation_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Saturation_04 sh -c 'docker run --gpus \"device=2\" --name jlehner_job23 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_saturation_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Saturation_06 sh -c 'docker run --gpus \"device=3\" --name jlehner_job24 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_saturation_06 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Saturation_08 sh -c 'docker run --gpus \"device=4\" --name jlehner_job25 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_saturation_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_CJ_Saturation_1 sh -c 'docker run --gpus \"device=5\" --name jlehner_job26 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=mnist_cj_saturation_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_svhn_no_augmentations sh -c 'docker run --gpus \"device=0\" --name jlehner_job1 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_no_aug --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_05 sh -c 'docker run --gpus \"device=1\" --name jlehner_job2 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_1 sh -c 'docker run --gpus \"device=2\" --name jlehner_job3 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_invert_05 sh -c 'docker run --gpus \"device=3\" --name jlehner_job4 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_invert_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_invert_1 sh -c 'docker run --gpus \"device=4\" --name jlehner_job5 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_invert_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_05_invert_05 sh -c 'docker run --gpus \"device=5\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_05_invert_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_1_invert_05 sh -c 'docker run --gpus \"device=6\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_1_invert_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_1_invert_1 sh -c 'docker run --gpus \"device=7\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_1_invert_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_05_invert_1 sh -c 'docker run --gpus \"device=0\" --name jlehner_job1 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_05_invert_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_02 sh -c 'docker run --gpus \"device=1\" --name jlehner_job2 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_04 sh -c 'docker run --gpus \"device=2\" --name jlehner_job3 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_06 sh -c 'docker run --gpus \"device=3\" --name jlehner_job4 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_06 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_08 sh -c 'docker run --gpus \"device=4\" --name jlehner_job5 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_1 sh -c 'docker run --gpus \"device=5\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_02 sh -c 'docker run --gpus \"device=6\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_04 sh -c 'docker run --gpus \"device=7\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_06 sh -c 'docker run --gpus \"device=0\" --name jlehner_job1 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_06 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_08 sh -c 'docker run --gpus \"device=1\" --name jlehner_job2 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_1 sh -c 'docker run --gpus \"device=2\" --name jlehner_job3 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Saturation_02 sh -c 'docker run --gpus \"device=3\" --name jlehner_job4 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_saturation_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Saturation_04 sh -c 'docker run --gpus \"device=4\" --name jlehner_job5 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_saturation_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Saturation_06 sh -c 'docker run --gpus \"device=5\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_saturation_06 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Saturation_08 sh -c 'docker run --gpus \"device=6\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_saturation_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Saturation_1 sh -c 'docker run --gpus \"device=7\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_saturation_1 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Hue_02 sh -c 'docker run --gpus \"device=0\" --name jlehner_job1 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_hue_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Hue_04 sh -c 'docker run --gpus \"device=1\" --name jlehner_job2 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_hue_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Hue_01 sh -c 'docker run --gpus \"device=2\" --name jlehner_job9 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_hue_01 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Hue_03 sh -c 'docker run --gpus \"device=3\" --name jlehner_job10 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_hue_03 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Hue_05 sh -c 'docker run --gpus \"device=4\" --name jlehner_job11 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_hue_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_01 sh -c 'docker run --gpus \"device=5\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_01 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_005 sh -c 'docker run --gpus \"device=6\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_005 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_03 sh -c 'docker run --gpus \"device=7\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_03 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_025 sh -c 'docker run --gpus \"device=0\" --name jlehner_job1 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_025 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_035 sh -c 'docker run --gpus \"device=1\" --name jlehner_job2 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_035 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_05 sh -c 'docker run --gpus \"device=2\" --name jlehner_job3 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Hue_03 sh -c 'docker run --gpus \"device=3\" --name jlehner_job4 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_hue_03 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Hue_05 sh -c 'docker run --gpus \"device=4\" --name jlehner_job5 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_hue_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_svhn_CJ_Brightness_02_Contrast_03 sh -c 'docker run --gpus \"device=5\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02_contrast_03 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_02_Contrast_04 sh -c 'docker run --gpus \"device=6\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02_contrast_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_02_Saturation_02 sh -c 'docker run --gpus \"device=7\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02_saturation_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_02_Saturation_08 sh -c 'docker run --gpus \"device=0\" --name jlehner_job1 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02_saturation_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_02_Contrast_05 sh -c 'docker run --gpus \"device=1\" --name jlehner_job2 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02_contrast_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_02_Hue_01 sh -c 'docker run --gpus \"device=2\" --name jlehner_job3 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02_hue_01 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_02_Hue_04 sh -c 'docker run --gpus \"device=3\" --name jlehner_job4 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02_hue_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_02_Invert_05 sh -c 'docker run --gpus \"device=4\" --name jlehner_job5 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_02_invert_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_01_Contrast_03 sh -c 'docker run --gpus \"device=5\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_01_contrast_03 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_01_Contrast_05 sh -c 'docker run --gpus \"device=6\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_01_contrast_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_01_Saturation_02 sh -c 'docker run --gpus \"device=7\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_01_saturation_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_01_Saturation_08 sh -c 'docker run --gpus \"device=0\" --name jlehner_job1 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_01_saturation_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_01_Hue_01 sh -c 'docker run --gpus \"device=1\" --name jlehner_job2 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_01_hue_01 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_01_Hue_04 sh -c 'docker run --gpus \"device=2\" --name jlehner_job3 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_01_hue_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Brightness_01_Invert_05 sh -c 'docker run --gpus \"device=3\" --name jlehner_job4 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_brightness_01_invert_05 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_03_Saturation_02 sh -c 'docker run --gpus \"device=4\" --name jlehner_job5 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_03_saturation_02 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_03_Saturation_08 sh -c 'docker run --gpus \"device=5\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_03_saturation_08 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_03_Hue_01 sh -c 'docker run --gpus \"device=6\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_03_hue_01 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_CJ_Contrast_03_Hue_04 sh -c 'docker run --gpus \"device=7\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_cj_contrast_03_hue_04 --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_svhn_adjust_sharpness_05_new sh -c 'docker run --gpus \"device=1\" --name jlehner_job1 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_05_new --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_1_new sh -c 'docker run --gpus \"device=2\" --name jlehner_job2 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_1_new --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_invert_05_new sh -c 'docker run --gpus \"device=3\" --name jlehner_job3 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_invert_05_new --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_invert_1_new sh -c 'docker run --gpus \"device=4\" --name jlehner_job4 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_invert_1_new --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_05_invert_05_new sh -c 'docker run --gpus \"device=5\" --name jlehner_job5 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_05_invert_05_new --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_1_invert_05_new sh -c 'docker run --gpus \"device=6\" --name jlehner_job6 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_1_invert_05_new --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_1_invert_1_new sh -c 'docker run --gpus \"device=7\" --name jlehner_job7 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_1_invert_1_new --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_adjust_sharpness_05_invert_1_new sh -c 'docker run --gpus \"device=0\" --name jlehner_job8 -it --rm -u `id -u $USER` -v /sybig/home/jlehner/code/FACT:/mnt jlehner_fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=svhn_adjust_sharpness_05_invert_1_new --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

'''


parser = argparse.ArgumentParser(description='PyTorch FACT Implementation')
parser.add_argument('--dataset', type=str, default='digit-five', metavar='N',
                    choices=['office', 'office-home', 'office_caltech_10', 'digit-five', 'domainNet', 'amazon_review'])
parser.add_argument('--target', type=str, default='', metavar='N', help='target domains (comma separated)')
parser.add_argument('--num_iter', type=int, default=0, metavar='N', help='number of iteration for training')
parser.add_argument('--epochs', type=int, default=1, metavar='N', help='epochs per round of training') #1 Epoch?
parser.add_argument('--rounds', type=int, default=1000, metavar='N', help='rounds of federated learning') #1000 Runden
parser.add_argument('--batch_size', type=int, default=16, metavar='N', help='batch size') #was ist eine Batch Size?
parser.add_argument('--lr', type=float, default=0.001, metavar='N', help='learning rate')
parser.add_argument('--name', type=str, default='', metavar='N', help='short description of the '
                                                                      'experiment you are running')
parser.add_argument('--exclude_domains', type=str, default='', metavar='N', help='domains from dataset that are '
                                                                                 'excluded from training '
                                                                                 '(comma separated)') #wieso wird etwas excluded?
parser.add_argument('--test_target', type=str, default='yes', metavar='N', help='test target clients in each round ('
                                                                                'yes/no)', choices=['yes', 'no']) #wann macht man das?
parser.add_argument('--test_source', type=str, default='no', metavar='N', help='test source clients in each round ('
                                                                               'yes/no)', choices=['yes', 'no'])
parser.add_argument('--remove_digits', type=str, default='', metavar='N', help='remove digits from the digit-five '
                                                                               'dataset (comma separated)')
parser.add_argument('--lr_decay_rate', type=float, default=0.75, metavar='N', help='learning rate decay rate')
parser.add_argument('--num_identical_domain_clients', type=int, default=1, metavar='N', help='use source clients from '
                                                                                             'the same domain')
parser.add_argument('--finetune', type=str, default='yes', metavar='N', help='use finetune step (yes/no)',
                    choices=['yes', 'no'])

device = "cuda" if torch.cuda.is_available() else "cpu" #cuda nutzt GPUs


def get_index_range(args, domain, i):
    if args.dataset in ['digit-five', 'office_caltech_10', 'office']:
        return range(
            i * int(dataset_domain_sample_count_mapping[args.dataset][domain] / args.num_identical_domain_clients),
            int(dataset_domain_sample_count_mapping[args.dataset][domain] / args.num_identical_domain_clients) * (
                    i + 1))
    else:
        return None


def get_source_clients(args):
    source_domains, _ = get_source_and_target_domains(args)

    source_clients = []
    for domain in source_domains:
        for i in range(args.num_identical_domain_clients):
            train_data, test_data = dataset_read(args.dataset, domain, args.batch_size, device,
                                                 index_range=get_index_range(args, domain, i))
            source_clients.append(
                Client(
                    dataset_name=args.dataset,
                    name=domain,
                    train_data=train_data,
                    test_data=test_data if arg_str_to_bool(args.test_source) else None,
                    G=get_dataset_specific_generator(args.dataset).to(device),
                    C2=get_dataset_specific_classifier(args.dataset).to(device),
                    source=True,
                    epochs=args.epochs,
                    rounds=args.rounds,
                    lr=args.lr,
                    device=device,
                    batch_size=args.batch_size,
                    lr_decay_rate=args.lr_decay_rate,
                )
            )
    return source_clients


def get_target_clients(args):
    _, target_domains = get_source_and_target_domains(args)
    target_clients = []
    for domain in target_domains:
        target_train_data, target_test_data = dataset_read(args.dataset, domain, args.batch_size, device)
        target_clients.append(
            Client(
                dataset_name=args.dataset,
                name=domain,
                train_data=target_train_data,
                test_data=target_test_data if arg_str_to_bool(args.test_target) else None,
                G=get_dataset_specific_generator(args.dataset).to(device),
                C1=get_dataset_specific_classifier(args.dataset).to(device),
                C2=get_dataset_specific_classifier(args.dataset).to(device),
                source=False,
                epochs=args.epochs,
                rounds=args.rounds,
                lr=args.lr,
                device=device,
                batch_size=args.batch_size,
                lr_decay_rate=args.lr_decay_rate,
            )
        )
    return target_clients


def main():
    args = parser.parse_args()
    torch.hub.set_dir("tmp/")
    torch.manual_seed(1)
    print("Iteration: ", args.num_iter) #args.num_iter ist default 0?
    server_name = f"FACT {args.name}, {args.dataset}, epochs={args.epochs}, rounds={args.rounds}, " \
                  f"bs={args.batch_size}, lr={args.lr}"

    source_clients = get_source_clients(args) #hat Daten von einer Domain, oben definiert
    target_clients = get_target_clients(args) #same aber ohne Labels
    feature_model = get_dataset_specific_generator(args.dataset).to(device)
    predictor_model = get_dataset_specific_classifier(args.dataset).to(device)

    server = Server(
        name=server_name,
        iteration=args.num_iter,
        target=args.target if args.exclude_domains == '' else args.target + f"_without_{args.exclude_domains}",
        source_clients=source_clients,
        target_clients=target_clients,
        feature_model=feature_model,
        predictor_model=predictor_model,
        rounds_of_fed_learning=args.rounds,
        epochs=args.epochs,
        finetune=arg_str_to_bool(args.finetune),
    )
    server.run()


if __name__ == "__main__":
    main()
